#!/bin/bash

if ! dpkg -l | grep -q -w "ncurses-utils"; then pkg install ncurses-utils -y; fi &>/dev/null

if [ ! -f dialogs ]; then
    curl -s -o dialogs https://raw.githubusercontent.com/GabiAle97/termux-box/main/scripts/dialogs &>/dev/null
    curl -s -o dialog.rc https://raw.githubusercontent.com/GabiAle97/termux-box/main/scripts/dialog.rc &>/dev/null
    curl -s -o loop https://raw.githubusercontent.com/GabiAle97/termux-box/main/scripts/loop &>/dev/null
    chmod +x loop
fi
. $HOME/dialogs

cd
dialog_loading "Asking for storage permission" &

sleep 5

if [ ! -e storage ]; then
    termux-setup-storage & &>/dev/null
    kill_current_dialog
    dialog_loading "Storage permission has not been granted." "Waiting for manually allowing" &
fi
while true; do
    if [ -e storage ]; then
        rm -rf /sdcard/termux-box
        break
    fi
done
sleep 5
kill_current_dialog

mkdir -p /sdcard/termux-box
touch /sdcard/termux-box/Installer.log
dialog_package_install "Termux-box MOD" "Updating termux packages" "pv" &
apt-get clean -y > /dev/null 2>&1
apt-get update -y > /dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade > /dev/null 2>&1
pkg install pv -y &>>/sdcard/termux-box/Installer.log
dialog_package_install "Termux-box MOD" "Installing necessary packages" "jq" &
pkg install x11-repo -y &>>/sdcard/termux-box/Installer.log
pkg install pulseaudio -y &>>/sdcard/termux-box/Installer.log
pkg install xwayland -y &>>/sdcard/termux-box/Installer.log
pkg install proot -y &>>/sdcard/termux-box/Installer.log
pkg install wget -y &>>/sdcard/termux-box/Installer.log
pkg install tsu -y &>>/sdcard/termux-box/Installer.log
pkg install root-repo -y &>>/sdcard/termux-box/Installer.log
pkg install jq -y &>>/sdcard/termux-box/Installer.log
dialog_progressbar_wget "Termux-box MOD" "Applying Termux Style" "https://github.com/GabiAle97/termux-box/releases/download/Dll_overrides/termux-style.tar.xz" "termux-style.tar.xz"
dialog_progressbar_tar "termux-style.tar.xz" "J"

. $HOME/termux-style/termux-style

apply-termux-style


rm -rf $HOME/termux-box
mkdir -p $HOME/termux-box
cd $HOME/termux-box
dialog_progressbar_wget "Termux-box MOD" "Obtaining & installing Termux-X11 server" "https://github.com/GabiAle97/termux-box/raw/main/components/termux-x11-1.02.07-0-all.deb" "termux-x11-1.02.07-0-all.deb"
dialog_progressbar_dpkg "termux-x11-1.02.07-0-all.deb"
rm -rf termux-x11-1.02.07-0-all.deb &>>/sdcard/termux-box/Installer.log


cd $HOME/termux-bo
dialog_menu "Termux-Box" "Download preconfigured Rootfs" \
"1" "Default Jammy (stable, missing libs)" \
"2" "Enhanced Mantic (Performance, useful for Wine-GE)" 
case $? in
1)
    dialog_progressbar_wget "Termux-box MOD" "Downloading Default Jammy" "https://github.com/GabiAle97/termux-box/releases/download/Dll_overrides/rootfs.tar.xz" "rootfs.tar.xz"
    export core=1
    ;;
2)
    dialog_progressbar_wget "Termux-box MOD" "Downloading Enhanced Mantic" "https://github.com/GabiAle97/termux-box/releases/download/Dll_overrides/rootfs-mantic.tar.xz" "rootfs.tar.xz"
    export core=2
    ;;
255)
    exit 0
    ;;
esac

dialog_progressbar_tar "rootfs.tar.xz" "J"
rm -rf rootfs.tar.xz &>>/sdcard/termux-box/Installer.log

cd $HOME/termux-box/ubuntu-fs/opt
if [ $core = 2 ]
then
    touch $HOME/termux-box/ubuntu-fs/opt/mantic-core-system
fi
dialog_progressbar_wget "Termux-box MOD" "Downloading scripts.tar.gz" "https://github.com/GabiAle97/termux-box/releases/download/mod_box/scripts.tar.gz" "scripts.tar.gz"
dialog_progressbar_tar "scripts.tar.gz" "z"
rm -rf scripts.tar.gz &>>/sdcard/termux-box/Installer.log

cd $HOME/termux-box
dialog_progressbar_wget "Termux-box MOD" "Downloading termux-box" "https://github.com/GabiAle97/termux-box/raw/main/scripts/termux-box" "termux-box"
chmod +x termux-box
mv termux-box $PREFIX/bin
dialog_progressbar_wget "Termux-box MOD" "Downloading start-proot.sh" "https://github.com/GabiAle97/termux-box/raw/main/scripts/start-proot.sh" "start-proot.sh"
dialog_progressbar_wget "Termux-box MOD" "Downloading start-chroot.sh" "https://github.com/GabiAle97/termux-box/raw/main/scripts/start-chroot.sh" "start-chroot.sh"
chmod +x start-proot.sh
chmod +x start-chroot.s
dialog_progressbar_wget "Termux-box MOD" "Downloading update-scripts" "https://github.com/GabiAle97/termux-box/raw/main/scripts/update-scripts" "update-scripts"
chmod +x update-scripts


cd $HOME/termux-box/ubuntu-fs/op
dialog_progressbar_wget "Termux-box MOD" "Downloading patch.tar.xz" "https://github.com/GabiAle97/termux-box/releases/download/Dll_overrides/patch.tar.xz" "patch.tar.xz"
rm -rf d3d &>>/sdcard/termux-box/Installer.log
rm -rf mesa &>/dev/nul
dialog_progressbar_tar "patch.tar.xz" "J"
rm -rf patch.tar.xz &>>/sdcard/termux-box/Installer.log

curl -s "https://api.github.com/repos/GloriousEggroll/wine-ge-custom/releases" | jq -r '.[].name' | wc -l > countge
curl -s "https://api.github.com/repos/Kron4ek/Wine-Builds/releases" | jq -r '.[].name' | wc -l > countkron
curl -s "https://api.github.com/repos/HansKristian-Work/vkd3d-proton/releases" | jq -r '.[].name' | wc -l > countvkd3d
expr $(cat countge) + $(cat countkron) > totalcount

cd
dialog_message "Termux-Box Mod" "Successfully installed!"

rm -rf "$0"
exec $PREFIX/bin/termux-box
