#!/bin/bash

export DIALOGRC=$HOME/dialog.rc
dialog_flags="--colors --output-fd 1 --erase-on-exit --no-shadow --cursor-off-label --no-kill"

function dialog_menu {
	tput civis
	result=$(dialog $dialog_flags --title "$1" --menu "$2

Select an option and click OK" 100 100 100 "${@:3}")
	if [ "$result" = "" ]; then result=255; fi
	tput cnorm
	return $result
}

function dialog_menu_item {
	tput civis
	result=$(dialog --default-item "$1" $dialog_flags --title "$2" --menu "$3

Select an option and click OK" 100 100 100 "${@:4}")
	if [ "$result" = "" ]; then result=255; fi
	tput cnorm
	return $result
}

function dialog_yesno {
	tput civis
	while true; do
		dialog --erase-on-exit --no-shadow --cursor-off-label --no-kill --no-cancel --title "$2" --yesno "$1" 0 0
		result=$?
		if ! [ "$result" = "255" ]; then return $result; fi
	done
	tput cnorm
}

function dialog_message {
	tput civis
	if [ $3 ]; then dialog --ok-label "$3" $dialog_flags --title "$1" --msgbox "$2" 0 0; else dialog $dialog_flags --title "$1" --msgbox "$2" 0 0; fi
	tput cnorm
}


function dialog_loading {
	export dialog_string_FL=$1
	export dialog_string_SL=$2
	export dialog_height=$(echo "$1" | grep -o "\n" | wc -l)
	export dialog_width_FL=$(echo "$1" | wc -m)
	export dialog_width_SL=$(echo "$2" | wc -m)
	export dialog_width_FL_height=$(echo "$1" | wc -l)
	export dialog_width_SL_height=$(echo "$2" | wc -l)
	if [ $dialog_width_FL -gt $dialog_width_SL ]; then
		export dialog_width=$dialog_width_FL
	else
		export dialog_width=$dialog_width_SL
	fi
    dialog --prgbox "./loop" $(expr 4 + $(expr $dialog_width_FL_height + $dialog_width_SL_height)) $(expr 4 + $dialog_width)
}

function kill_current_dialog {
	dialog_pid=$(ps a | grep -m 1 "dialog --prgbox ./loop" | awk -F " " '{print $1}')
	kill $dialog_pid &>>/sdcard/termux-box/Installer.log
	stty sane
}

function dialog_progressbar_wget {
	file_url="$3"
	output_file="$4"

	wget "$file_url" -O "$output_file" 2>&1 | \
    grep "%" | \
    awk '{print $7}' | \
	awk -F "%" '{print $1}' | \
	dialog --title "$1" --gauge "$2" 10 60 0
}

function dialog_package_install {
    local timer=0
    while ! dpkg -l | grep -q -w "$3" 2>/dev/null; do
        echo $timer
        sleep 2
        export timer=$(expr $timer + 3)
		if dpkg -l | grep -q -w "$3"; then echo "100"; fi
    done | dialog --title "$1" --gauge "$2..." 0 0 0
}

function dialog_progressbar_tar {
	(pv -n $1 | tar x${2}f - ) 2>&1 | dialog --title "Termux-box MOD" --gauge "Extracting $1..." 6 50
}

function dialog_progressbar_dpkg {
    {
		dpkg -i $1 &
        dpkg_pid=$!
		counter=0
        while ps -p $dpkg_pid > /dev/null; do
			echo "$counter"
			counter=$(expr $counter + 8)
			sleep 1
            if ! ps -p $dpkg_pid > /dev/null; then echo "100"; fi
        done
    } | dialog --title "Termux-box MOD" --gauge "Installing $1..." 0 0
}