#!/bin/bash

counter=1
counter_anim=1
while [ $kill_dialog = 0 ]; do
    loading_animation=""
    counter_string=1
    for (( i=0; i<${#dialog_string_FL}; i++ )); do
        if [ $counter_string = $(expr  $dialog_width / 2) ]; then
            if [ $counter_anim = 1 ]; then
                loading_animation+="-"
            elif [ $counter_anim = 2 ]; then
                loading_animation+="\\"
            elif [ $counter_anim = 3 ]; then
                loading_animation+="|"
            elif [ $counter_anim = 4 ]; then
                loading_animation+="/"
                counter_anim=0
            fi
            counter_anim=$(expr $counter_anim + 1)
        else
            loading_animation+=" "
        fi
        counter_string=$(expr $counter_string + 1)
    done
    counter_string=1
    echo "$dialog_string_FL"
    echo "$dialog_string_SL"
    echo ""
    echo "$loading_animation"
    loading_animation=""
    sleep 1
done