#!/bin/bash

cd $HOME/termux-box/ubuntu-fs/opt

wget https://github.com/GabiAle97/termux-box/raw/WoW64/scripts/scripts.tar.gz &>>/sdcard/termux-box/Installer.log
mkdir tempscripts
tar -xf scripts.tar.gz -C tempscripts
rm -rf scripts.tar.gz

cd tempscripts
cp -n *.conf .. &>>/sdcard/termux-box/Installer.log
cp Env.conf /sdcard/termux-box
cp Env.conf ..
cp vkd3d.conf /sdcard/termux-box
cp vkd3d.conf ..
rm -rf *.conf
mv * ..
cd ..
rm -rf tempscripts

cd $HOME/termux-box/

wget -N https://github.com/GabiAle97/termux-box/raw/WoW64/scripts/termux-box &>>/sdcard/termux-box/Installer.log
chmod +x termux-box
mv termux-box $PREFIX/bin/
wget -N https://github.com/GabiAle97/termux-box/raw/WoW64/scripts/start-proot.sh &>>/sdcard/termux-box/Installer.log
wget -N https://github.com/GabiAle97/termux-box/raw/WoW64/scripts/start-chroot.sh &>>/sdcard/termux-box/Installer.log
chmod +x start-proot.sh
chmod +x start-chroot.sh

cd $HOME/termux-box/ubuntu-fs/opt
touch prefix-apply-patch

rm -rf patch.tar.xz
wget -q --show-progress https://github.com/GabiAle97/termux-box/releases/download/Dll_overrides/patch.tar.xz
rm -rf d3d
rm -rf mesa
tar -xf patch.tar.xz
rm -rf patch.tar.xz

cd
rm -rf "$0"