#!/bin/bash

cd $HOME/termux-box

. $HOME/termux-box/ubuntu-fs/opt/termux-style/termux-style

. $HOME/termux-box/ubuntu-fs/opt/dialogs

apply-termux-style

if [ ! -e ubuntu-fs/opt/wine ]; then
    dialog_menu "Termux-Box" "Select which Wine to download: " \
    "1" "8.19 staging" \
    "2" "8.22 ge-custom" \
    "3" "8.0 proton experimental"
    case $? in
    1)
        dialog_loading "Downloading Wine 8.19 staging" &
        loading_process=$!
        wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/8.19/wine-8.19-staging-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz &>/dev/null
        if [ ! -f ubuntu-fs/opt/wine.tar.xz ]; then
            echo "Download failed, restart termux-box"
            exit
        fi
        kill $loading_process
        ;;
    2)
        dialog_loading "Downloading Wine 8.22 ge-custom" &
        loading_process=$!
        wget -q --show-progress https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-22/wine-lutris-GE-Proton8-22-x86_64.tar.xz -O ubuntu-fs/opt/wine.tar.xz &>/dev/null
        if [ ! -f ubuntu-fs/opt/wine.tar.xz ]; then
            echo "Download failed, restart termux-box"
            exit
        fi
        kill $loading_process
        ;;
    3)
        dialog_loading "Downloading Wine 8.0 proton experimental" &
        loading_process=$!
        wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/proton-exp-8.0/wine-proton-exp-8.0-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz &>/dev/null
        if [ ! -f ubuntu-fs/opt/wine.tar.xz ]; then
            echo "Download failed, restart termux-box"
            exit
        fi
        kill $loading_process
        touch ubuntu-fs/opt/patch-re8
        ;;
    esac
fi

. $HOME/termux-box/update-scripts

sleep 0.5

if [ ! -L $HOME/termux-box/ubuntu-fs/opt/prefix-tweaks/dosdevices/f: ]; then
    ln -s /external/Download $HOME/termux-box/ubuntu-fs/opt/prefix-tweaks/dosdevices/f:
fi

cd $HOME/termux-box
touch ubuntu-fs/root/.hushlogin
mkdir -p /sdcard/Android/data/com.termux/files/Download &>/dev/null
mkdir -p ubuntu-fs/external &>/dev/null
termux-x11 :1 &>/dev/null &
rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

mkdir /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/Env.conf /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/dxvk.conf /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/vkd3d.conf /sdcard/termux-box >/dev/null 2>&1
negus=$(cat ubuntu-fs/opt/script.conf)
if [ "$negus" = "" ]; then
    dialog_menu "Termux-Box" "Select containerization method" \
    "1" "Proot" \
    "2" "Chroot (root only)"
    export oleg=$?
elif [ "$negus" = "proot" ]; then
    oleg=1
else
    oleg=2
fi
case $oleg in
1)
    echo "proot">ubuntu-fs/opt/script.conf
        ./start-proot.sh
    ;;
2)
    echo "chroot">ubuntu-fs/opt/script.conf
    sudo chown -hR root:root ubuntu-fs/root
    sudo ./start-chroot.sh
    prootuser=$(id -u)
    sudo chown -hR $prootuser:$prootuser ubuntu-fs
    ;;
esac

rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pkill -f pulseaudio
pkill -f proot
pkill -f "app_process / com.termux.x11"

restore-termux-style

if [ -e ~/termux-box/ubuntu-fs/opt/restart-termux-box ]; then
    rm -rf ~/termux-box/ubuntu-fs/opt/restart-termux-box
    exec $0
fi
