#!/bin/bash

cd $HOME/termux-box

. $HOME/termux-style/termux-style

. $HOME/dialogs

apply-termux-style

if [ ! -e ubuntu-fs/opt/wine ]; then
    dialog_menu "Termux-box MOD-WoW64" "Select which Wine to download: " \
    "1" "9.3 staging" \
    "2" "9.4 staging-tkg" \
    "3" "Proton 9.0 Bleeding-Edge"
    case $? in
    1)
        dialog_progressbar_wget "Install Custom Wine" "Downloading Wine 9.3 staging" "https://github.com/GabiAle97/Wine-WoW64-Builds/releases/download/Wine9.3/wine-9.3-exp-wow64-amd64.tar.xz" "ubuntu-fs/opt/wine.tar.xz"
        ;;
    2)
        dialog_progressbar_wget "Install Custom Wine" "Downloading Wine 9.4 staging-tkg" "https://github.com/GabiAle97/Wine-WoW64-Builds/releases/download/Wine9.4/wine-9.4-staging-tkg-exp-wow64-amd64.tar.xz" "ubuntu-fs/opt/wine.tar.xz"
        ;;
    3)
        dialog_progressbar_wget "Install Custom Wine" "Downloading Wine Proton 9.0 Bleeding Edge" "https://github.com/GabiAle97/Wine-WoW64-Builds/releases/download/Proton9.0-BE/wine-proton-exp-9.0-fd4a312a302-exp-wow64-amd64.tar.xz" "ubuntu-fs/opt/wine.tar.xz"
        touch ubuntu-fs/opt/patch-re8
        ;;
    esac
fi

. $HOME/termux-box/update-scripts

sleep 0.5

if [ ! -L $HOME/termux-box/ubuntu-fs/opt/prefix-tweaks/dosdevices/f: ]; then
    ln -s /external/Download $HOME/termux-box/ubuntu-fs/opt/prefix-tweaks/dosdevices/f:
fi

cd $HOME/termux-box
touch ubuntu-fs/root/.hushlogin
mkdir -p /sdcard/Android/data/com.termux/files/Download &>>/sdcard/termux-box/Installer.log
mkdir -p ubuntu-fs/external &>>/sdcard/termux-box/Installer.log
termux-x11 :1 &>>/sdcard/termux-box/Installer.log &
rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

mkdir /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/Env.conf /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/dxvk.conf /sdcard/termux-box >/dev/null 2>&1
cp -n ubuntu-fs/opt/vkd3d.conf /sdcard/termux-box >/dev/null 2>&1
negus=$(cat ubuntu-fs/opt/script.conf)
if [ "$negus" = "" ]; then
    dialog_menu "Termux-box MOD-WoW64" "Select containerization method" \
    "1" "Proot" \
    "2" "Chroot (root only)"
    export oleg=$?
elif [ "$negus" = "proot" ]; then
    oleg=1
else
    oleg=2
fi
case $oleg in
1)
    echo "proot">ubuntu-fs/opt/script.conf
        ./start-proot.sh
    ;;
2)
    echo "chroot">ubuntu-fs/opt/script.conf
    sudo chown -hR root:root ubuntu-fs/root
    sudo ./start-chroot.sh
    prootuser=$(id -u)
    sudo chown -hR $prootuser:$prootuser ubuntu-fs
    ;;
esac

rm -rf $PREFIX/tmp/pulse-*
pulseaudio -k >/dev/null 2>&1
pkill -f pulseaudio
pkill -f proot
pkill -f "app_process / com.termux.x11"

restore-termux-style

if [ -e ~/termux-box/ubuntu-fs/opt/restart-termux-box ]; then
    rm -rf ~/termux-box/ubuntu-fs/opt/restart-termux-box
    exec $0
fi
