#!/bin/bash

if [ ! -f latest_commit.txt ]
then
    curl -s "https://api.github.com/repos/GabiAle97/termux-box/commits?path=scripts&per_page=1" | jq -r '.[0].sha' > latest_commit.txt
fi

# Get the latest commit SHA from the repository
latest_commit=$(curl -s "https://api.github.com/repos/GabiAle97/termux-box/commits?path=scripts&per_page=1" | jq -r '.[0].sha')

# Check if the latest commit SHA is different from the one you have
if [ "$latest_commit" != "$(cat latest_commit.txt 2>/dev/null)" ]; then
  
  dialog_yesno "Do you want to perform a FULL update of termux-box now?" "There is a new commit!"
  if [ "$?" = "0" ]; then
		rm $HOME/termux-box/ubuntu-fs/opt/updated-ubuntu
    cd ~/
    curl -o install https://raw.githubusercontent.com/GabiAle97/termux-box/main/install && chmod +x install && ./install
    echo "$latest_commit" > latest_commit.txt
	fi
fi

if [ ! -f latest_release.txt ]
then
    curl -s "https://api.github.com/repos/GabiAle97/termux-box/releases/latest" | jq -r '.assets[] | select(.name == "scripts.tar.gz").updated_at' > latest_release.txt
fi

# Get the latest release tag from the repository
latest_release=$(curl -s "https://api.github.com/repos/GabiAle97/termux-box/releases/latest" | jq -r '.assets[] | select(.name == "scripts.tar.gz").updated_at')

# Check if the latest release tag is different from the one you have
if [ "$latest_release" != "$(cat latest_release.txt 2>/dev/null)" ]; then
  
  dialog_yesno "It's STRONGLY recommended to update this, since it would come with some new functions and wine-custom versions, but it isn't mandatory if you're happy with the actual performance." "There is a new release!"
  if [ "$?" = "0" ]
  then 
      cd $HOME/termux-box/ubuntu-fs/opt/
      for file in *.conf; do
        filename=$(basename "$file" .conf)
        mv "$file" "$filename.conf.backup"
      done
      cd $HOME/termux-box/ubuntu-fs/opt/dynarec
      for file in *.conf; do
        filename=$(basename "$file" .conf)
        mv "$file" "$filename.conf.backup"
      done
      cd $HOME/termux-box/ubuntu-fs/opt/
      wget https://github.com/GabiAle97/termux-box/releases/download/mod_box/scripts.tar.gz
      tar -xf scripts.tar.gz
      rm -rf scripts.tar.gz
      for file in *.conf.backup; do
        filename=$(basename "$file" .conf.backup)
        mv "$file" "$filename.conf"
      done
      cd $HOME/termux-box/ubuntu-fs/opt/dynarec
      for file in *.conf; do
        filename=$(basename "$file" .conf)
        mv "$file" "$filename.conf.backup"
      done
      cd $HOME/termux-box/ubuntu-fs/opt/
      echo "$latest_release" > $HOME/termux-box/latest_release.txt
  fi
  cd ~
  touch $HOME/termux-box/ubuntu-fs/opt/scripts-updated
fi

if [ ! -f latest_patch.txt ]
then
    curl -s "https://api.github.com/repos/GabiAle97/termux-box/releases/124714593" | jq -r '.assets[] | select(.name == "patch.tar.xz").updated_at' > latest_patch.txt
fi

# Get the latest release tag from the repository
latest_patch=$(curl -s "https://api.github.com/repos/GabiAle97/termux-box/releases/124714593" | jq -r '.assets[] | select(.name == "patch.tar.xz").updated_at')

# Check if the latest release tag is different from the one you have
if [ "$latest_patch" != "$(cat latest_patch.txt 2>/dev/null)" ]; then
  dialog_yesno "It's STRONGLY recommended to update this, since it would come with some fixes and/or new turnip/dxvk/vkd3d/wined3d versions, but it isn't mandatory if you're happy with the actual performance." "There is a new patch!"
  if [ "$?" = "0" ]
  then 
      cd $HOME/termux-box/ubuntu-fs/opt
      wget -q https://github.com/GabiAle97/termux-box/releases/download/Dll_overrides/patch.tar.xz &>/dev/null
      rm -rf d3d &>/dev/null
      rm -rf mesa &>/dev/null
      tar -xf patch.tar.xz &>/dev/null
      rm -rf patch.tar.xz &>/dev/null
      cd
      echo "$latest_patch" > $HOME/termux-box/latest_patch.txt
  fi
  cd ~
  touch $HOME/termux-box/ubuntu-fs/opt/scripts-updated
fi